repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5120']

-   repo: local
    hooks:
    -   id: format
        name: format
        entry: poetry run format
        language: system
        types: [python]
        files: ^auto_prep/.*\.py$
        pass_filenames: false

    -   id: lint
        name: lint
        entry: poetry run lint
        language: system
        types: [python]
        files: ^auto_prep/.*\.py$
        pass_filenames: false
