name: Docs2Pages
on:
  push:
    tags: '*'
    branches:
      - dev

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - uses: abatilo/actions-poetry@v2.1.3
      with:
        python-version: "3.10"
        poetry-version: "1.8.5"

    - name: install
      run: poetry install -E docs

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        poetry run sphinx-apidoc -o docs auto_prep --force
        poetry run make -C docs clean
        poetry run make -C docs html
        cp -r docs/_build/html/* gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
